/**
 * Core user entity returned by the backend.
 */
export type User = {
    /**
     * Unique user identifier.
     */
    id: string;

    /**
     * Full display name.
     */
    name: string;

    /**
     * Primary email address.
     */
    email: string;

    /**
     * Optional phone number.
     */
    phone?: string;

    /**
     * User role used for authorization.
     */
    role: 'admin' | 'manager' | 'user';

    /**
     * Current account status.
     */
    status: 'active' | 'inactive' | 'suspended';

    /**
     * Optional profile image URL.
     */
    avatarUrl?: string;

    /**
     * Whether the email has been verified.
     */
    emailVerified: boolean;

    /**
     * Account creation timestamp.
     */
    createdAt: string;

    /**
     * Last profile update timestamp.
     */
    updatedAt: string;
};

/**
 * Payload used when creating a new user.
 *
 * Excludes:
 * - autogenerated fields
 * - server-managed metadata
 */
export type CreateUserPayload = {
    name: string;
    email: string;
    password: string;
    phone?: string;
    role?: 'admin' | 'manager' | 'user';
};

/**
 * Payload used for updating existing users.
 *
 * Partial allows updating only changed fields.
 */
export type UpdateUserPayload =
    Partial<
        Omit<
            CreateUserPayload,
            'password'
        >
    > & {
        password?: string;
    };